### ISSUE TITLE
Text is messed up and not saved

### ISSUE THREAD

**Issue by nitaku** [nitaku/TEA#23]
The application stops saving and begins to write text backwards (!!!).

**Comment by fabiovalse** [comment]
Still there is the empty id response problem after some PUT requests have been correctly made.

**Comment by nitaku** [comment]
Solved in 9983c2a700d67d1aa43d67313cd75066aa1727e5 and in https://github.com/nitaku/annotarium/commit/ef19763bd86b817c62cd1c3b760122bcf2aa1805
