### ISSUE TITLE
Multiline annotation

### ISSUE THREAD

**Issue by angelodel80** [nitaku/TEA#5]
properly handling multiline annotations

**Comment by nitaku** [comment]
Syntax highlighting is broken, while actual parsing is fine.

**Comment by nitaku** [comment]
It seems that all the offset accounting in Document.coffee is broken. We have to reimplement it all to parse event by event (e.g, TEXT, SPAN_OPEN, TEXT, SPAN_CLOSE, ...).

**Comment by nitaku** [comment]
Solved in 60de64dec818d8ade6e126becf20e8eed55d4f56 with the introduction of the new parser
